### ISSUE TITLE
How to join this organization?

### ISSUE THREAD

**Issue by khushimarothi** [DevScript/Event-Build-Personal-Portfolio#17]

**Comment by VedantKhairnar** [comment]
@khushimarothi 
Do you wish to join the GitHub Organisation or be a part of the community, or be a part of the team?

**Comment by khushimarothi** [comment]
Github organization as well as part of community 

> @khushimarothi Do you wish to join the GitHub Organisation or be a part of the community, or be a part of the team?

**Comment by VedantKhairnar** [comment]
There's neither a criterion nor a process for joining the community.
What's your objective for joining the GitHub org?
